config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    collection do
      get :search
    end
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
        post :status_toggle
      end
      resources :resumes
    end
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  has_many :resumes

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  def publish!
    self.update_attribute(:is_hidden, false)
  end

  def hide!
    self.update_attribute(:is_hidden, true)
  end

  def toggle_status!
    if is_hidden
      publish!
    else
      hide!
    end
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader


  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :resumes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin

  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.recent.paginate(page: params[:page], per_page: 20)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  def status_toggle
    @job = Job.find(params[:id])
    @job.toggle_status!
    respond_to do |format|
      format.json { render json: @job }
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    unless current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end
    @jobs = jobs.paginate(page: params[:page], per_page: 10)
  end

  def search
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    search_criteria = { title_or_description_cont: @query_string }

    @q = Job.published.ransack(search_criteria)

    @jobs = @q.result(distinct: true).paginate(page: params[:page], per_page: 20)
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This Job already archived"
      redirect_to root_path
    end
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout 'welcome'

  def index

  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper

  def render_job_status(job)
    if job.is_hidden
      fa_icon 'lock', id: "job_status_icon_#{job.id}"
    else
      fa_icon 'unlock', id: "job_status_icon_#{job.id}"
    end
  end

end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_highlight_content(content, query_string)
    excerpt_cont = excerpt(content, query_string, radius: 500)
    if excerpt_cont
      highlight(excerpt_cont, query_string)
    else
      content
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.slim
h1 Edit a job

= simple_form_for [:admin, @job] do |f|
  = f.input :title, label: '岗位名称'
  = f.input :description, label: '岗位介绍'
  = f.input :wage_lower_bound, label: '薪资下限'
  = f.input :wage_upper_bound, label: '薪资上限'
  = f.input :contact_email, label: '联系邮箱'
  = f.input :is_hidden, label: '是否隐藏?'

  = f.submit 'Submit'

app/views/admin/jobs/index.html.slim
button.ui.right.floated.primary.basic.button
  a[href='/admin/jobs/']
    = semantic_icon 'add circle'
    | 发布岗位
table.ui.teal.celled.striped.table
  thead
    tr
      th 发布日期
      th 岗位名称
      th 简历数量
      th 薪资下限
      th 薪资上限
      th[colspan="3"] 管理选项
  tbody#admin_job_list
    - @jobs.each do |job|
      tr
        td
          = job.created_at.to_date
        td
          => render_job_status job
          =< link_to job.title, admin_job_path(job)
        td
          = link_to job.resumes.count, admin_job_resumes_path(job)
        td
          = job.wage_lower_bound
        td
          = job.wage_upper_bound
        td 
          => link_to fa_icon('pencil') + ' 编辑', edit_admin_job_path(job), class: 'ui blue button'
          => link_to fa_icon('trash-o') + ' 删除', admin_job_path(job), method: :delte, class: 'ui red button'
          .ui.toggle.checkbox
            = check_box_tag "job_status", status_toggle_admin_job_path(job), !job.is_hidden, { "data-job-id": job.id }
            label 公开
= will_paginate @collection, renderer: WillPaginateSemanticUi::ActionView::Renderer

javascript:
	$('#admin_job_list .checkbox').checkbox({
		onChange: function() {
      var job_id = $(this).data('job-id');
      var toggle_url = $(this).attr('value');
      var job_slide = $(this).parent();
      $.ajax({
        url: toggle_url,
        type: 'post',
        dataType: 'json',
        success: function(job) {
          var job_icon = $('#job_status_icon_'+job_id);
          if(job.is_hidden){
            job_icon.attr('class', 'fa fa-lock');
            job_slide.checkbox('uncheck');
          } else {
            job_icon.attr('class', 'fa fa-unlock');
            job_slide.checkbox('check');
          }
        }
      });
		}
	});

app/views/admin/jobs/new.html.slim
h1 Add a job

= simple_form_for [:admin, @job] do |f|
  = f.input :title, label: '岗位名称'
  = f.input :description, label: '岗位介绍'
  = f.input :wage_lower_bound, label: '薪资下限'
  = f.input :wage_upper_bound, label: '薪资上限'
  = f.input :contact_email, label: '联系邮箱'
  = f.input :is_hidden, label: '是否隐藏?'

  = f.submit 'Submit'

app/views/admin/jobs/show.html.slim
h1 
  = @job.title

p
  = simple_format @job.description

app/views/admin/resumes/_resume.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-12
        h3.panel-title 
          = resume.user.email
  .panel-body
    .trix-content
      p
        = simple_format(resume.content)
    hr
    - if resume.attachment.present?
      = fa_icon 'paperclip'
      = link_to 'Download Resume', resume.attachment_url
    - else
      | No Attachment

app/views/admin/resumes/index.html.slim
h2
  = @job.title
  | - 简历列表

hr

= render partial: 'resume', collection: @resumes, as: :resume

app/views/common/_flashes.html.slim
- if flash.any?
  .ui.container
  - user_facing_flashes.each do |msg_type, msg|
    | <div class="alert alert-dismissable alert-
    = flash_class(msg_type)
    | " role="alert" style="border: 0;">
    button.close[data-dismiss="alert"]
      span[aria-hidden='true'] &times;
    = msg
    | </div>

app/views/common/_footer.html.slim
.ui.inverted.footer.segment
  .ui.stackable.inverted.divided.grid
    .six.wide.column.center.aligned
      .ui.inverted.segment
        | Copyright &copy;2017 高就 all right reserved by imtinge
    .nine.wide.column.center.aligned
      .ui.inverted.horizontal.link.list
        = link_to semantic_icon('big weibo'), 'https://weibo.com/imtinge', target: '_blank', class: 'item'
        = link_to semantic_icon('big github'), 'https://github.com/imtinge', target: '_blank', class: 'item'
        = link_to semantic_icon('big bitbucket'), 'https://bitbucket.com/imtinge', target: '_blank', class: 'item'
    .one.wide.column.center.aligned
      .ui.inverted.link.list
        = link_to semantic_icon('big thumbs outline up'), 'https://fullstack.xinshengdaxue.com/works/294', target: '_blank', class: 'item'

app/views/common/_navbar.html.slim
.ui.large.fixed.inverted.menu#navbar
  | <a target='_blank' href="https://github.com/imtinge/GaoJob"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png"></a>
  .ui.container
    a.header.item[href='/']
      = semantic_icon 'inverted teal large map outline'
      span[style='font-size: 2em;']
        | &nbsp;
        | 高就
    .right.menu
      .item
        .ui.transparent.inverted.icon.input
          = semantic_icon 'search'
          input[type='text' placeholder='Search']
      - unless user_signed_in?
        .item
          = link_to 'Log in', new_user_session_path, class: 'ui inverted button', 'data-turbolinks': "false"
        .item
          = link_to 'Sign up', new_user_registration_path, class: 'ui inverted button', 'data-turbolinks': "false"
      - else
        .ui.simple.dropdown.item[tabindex='0']
          = current_user.email
          i.dropdown.icon
          .menu[tabindex='-1']
            = link_to 'Admin panel', admin_jobs_path, class: 'item', 'data-turbolinks': "false"
            = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'item', 'data-turbolinks': "false"

app/views/common/_search_bar.html.slim
= form_tag search_jobs_path, method: :get, class: 'navbar-form navbar-right' do
  .input-group
    = text_field_tag :q, nil, class: 'form-control', placeholder: '查找工作'
    span.input-group-btn
      button.btn.btn-default[type='submit']
        span.glyphicon.glyphicon-search

app/views/jobs/_job.html.slim
.ui.piled.segment
  = link_to job.title, job_path(job), class: 'ui big teal ribbon label'
  .ui.header
    .ui.top.right.attached.label
      => fa_icon 'clock-o'
      |
      = local_time(job.created_at).to_date
  .ui.grid
    .five.wide.column
      = fa_icon 'rmb'
      = job.wage_lower_bound
      | ~
      = job.wage_upper_bound
    .five.wide.column
      => semantic_icon 'building outline'
      = job.company_name
    .five.wide.column
      => semantic_icon 'marker'
      = job.location

app/views/jobs/edit.html.slim
h1 Edit a job

= simple_form_for @job do |f|
  = f.input :title, label: '岗位名称'
  = f.input :description, label: '岗位介绍'
  = f.input :wage_lower_bound, label: '薪资下限'
  = f.input :wage_upper_bound, label: '薪资上限'
  = f.input :contact_email, label: '联系邮箱'
  = f.input :is_hidden, label: '是否隐藏?'

  = f.submit 'Submit'

app/views/jobs/index.html.slim
.ui.container
  .ui.hidden.divider
  .ui.simple.dropdown.button
    .text
      | 排序
    = semantic_icon 'dropdown'
    .menu
      = link_to "按照薪资下限排序", jobs_path(:order => "by_lower_bound"), class: 'item'
      = link_to "按照薪资上限排序", jobs_path(:order => "by_upper_bound"), class: 'item'
      = link_to "按发布时间排序", jobs_path(:order => "by_upper_bound") , class: 'item'
.ui.container
  ul
    = render partial: 'job', collection: @jobs, as: :job
.ui.center.aligned.container
  = will_paginate @collection, renderer: WillPaginateSemanticUi::ActionView::Renderer

app/views/jobs/new.html.slim
h1 Add a job

= simple_form_for @job do |f|
  = f.input :title, label: '岗位名称'
  = f.input :description, label: '岗位介绍'
  = f.input :wage_lower_bound, label: '薪资下限'
  = f.input :wage_upper_bound, label: '薪资上限'
  = f.input :contact_email, label: '联系邮箱'
  = f.input :is_hidden, label: '是否隐藏?'

  = f.submit 'Submit'

app/views/jobs/search.html.slim
h2 查找结果
.search-info-title
- if @query_string.blank?
  | 对不起，查询内容不能为空，请输入工作岗位名称或描述
- elsif @jobs.empty?
  | 对不起，找不到有关#{@query_string}的工作
- else
.search-result
  table.table.table-boldered
    thead
      tr
        th 发布日期
        th 岗位名称
        th 岗位描述
        th 薪资下限
        th 薪资上限
    tbody
      - @jobs.each do |job|
        tr
          td
            = local_time(job.created_at).to_date
          td
            = link_to render_highlight_content(job.title, @query_string), job_path(job)
          td
            = link_to render_highlight_content(job.description, @query_string)
          td
            = link_to job.wage_lower_bound
          td
            = link_to job.wage_upper_bound
  .container.text-center
    = will_paginate @jobs, renderer: BootstrapPagination::Rails

app/views/jobs/show.html.slim
.ui.container[style='min-height: 610px;']
  .ui.raised.segment
    h1.header
      = @job.title
    = simple_format @job.description
    .text-center
      = link_to '投交简历', new_job_resume_path(@job), style: 'font-size: 30px; text-decoration: underline;'

app/views/layouts/admin.html.slim
doctype html
html
  head
    title 在这高就
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag
  body
    = render 'common/navbar'
    #main.fluid.container
      / = semantic_flash
      .ui.hidden.divider
      .ui.container
        .ui.grid
          .three.wide.column
            .ui.teal.vertical.menu
              a.active.item[href='/admin/jobs/']
                | Admin panel
              a.item[href='/jobs']
                | Job list
          .thirteen.wide.column
            = yield
      / = render 'common/tawk'
      = render 'common/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    title 在这高就
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag
  body
    = render 'common/navbar'
    = render 'common/flashes'
    .row[style='margin-top: 80px;']
      = yield
    = render 'common/footer'

app/views/layouts/welcome.html.slim
doctype html
html
  head
    title 在这高就
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag
  body
    = render 'common/navbar'
    .fluid.container
      / = semantic_flash
      = yield
      / = render 'common/tawk'
      = render 'common/footer'

app/views/resumes/new.html.slim
.container[style='margin-bottom: 80px;']
  h3 投交简历到
  = @job.title
  hr
  = simple_form_for [@job, @resume] do |f|
    = f.input :content
    = f.input :attachment
    = f.submit '送出'

app/views/welcome/index.html.slim
.ui.center.aligned.segment#welcome-bg
  .ui.huge.inverted.header
    h1[style='font-size: 2em;']
      | 高就
    h1 
      |找工作，从未如此迅捷
    h1
      | 让你快速找到属于你的优质工作,
      | 从此高枕无忧，东成西就
  .ui.huge.green.button
    = link_to '高就之路，从之开始', jobs_path, style: 'color: #fff', "data-turbolinks": "false"


javascript:
  $(document).ready(function() {
    $('#navbar').css('background', 'transparent');
  });

  $(window).scroll(function() {
    var value = $(this).scrollTop();
    if (value > 70)
      $('#navbar').css('background', '#1B1C1D');
    else
      $('#navbar').css('background', 'transparent');
  });